---
Name: graphql-devtool-routes
After:
  - 'graphql-dev'
---
SilverStripe\GraphQL\Dev\DevelopmentAdmin:
  registered_controllers:
    ide:
      controller: 'SilverStripe\GraphQLDevTools\Controller'
      links:
        ide: Run the GraphQL IDE
SilverStripe\GraphQLDevTools\Controller:
  default_route: 'graphql'
